# ----------------------------------------------------------------------------------
# Theme basic info (please don't change)
# ----------------------------------------------------------------------------------
theme_info:
  name: ILS
  version: 2.0.2
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils


# ----------------------------------------------------------------------------------
# Theme style settings
# ----------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066CC"

  # favicon
  favicon: images/favicon.jpg

  # avatar
  avatar: images/avatar.jpg


# ----------------------------------------------------------------------------------
# Navigation menu
# ----------------------------------------------------------------------------------
menu:
  Home: /
  Archives: /archives
  # Categories: /categories
  # Tags: /tags
  # Links: /links
  About: /about
  # ...


# ----------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ----------------------------------------------------------------------------------
rss:
  enable: false


# ----------------------------------------------------------------------------------
# Comment plugin
# ----------------------------------------------------------------------------------
comments:
  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    enable: false
    appid:                # your leancloud application appid
    appkey:               # your leancloud application appkey
    meta:                 # comment input meta, type: Array, values: ['nick','mail','link']
    placeholder:          # your placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id:             # GitHub repo owner
    repository:            # Repository name to store issues
    client_id:             # GitHub Application Client ID
    client_secret:         # GitHub Application Client Secret


# ----------------------------------------------------------------------------------
# Website count
# ----------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false


# ----------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ----------------------------------------------------------------------------------
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  unescape: false

  # Preload the search data when the page loads.
  preload: false


# ----------------------------------------------------------------------------------
# Post word count
# Dependencies: hexo-wordcount
# See: https://github.com/willin/hexo-wordcount
# ----------------------------------------------------------------------------------
post_wordcount:
  enable: false
  wordcount: false  # word count, one article
  min2read: false   # time to read, one article


# ----------------------------------------------------------------------------------
# Home page article block display settings
# ----------------------------------------------------------------------------------
home_article:
  category:
    enable: false     # show category in home page article block
    limit: 3          # max number of categories shown in home page article block
  tag:
    enable: false     # show tags in home page article block
    limit: 5          # max number of tags shown in home page article block


# ----------------------------------------------------------------------------------
# Code copy
# ----------------------------------------------------------------------------------
code_copy:
  enable: true
  style: flat        # values: default | flat | mac


# ----------------------------------------------------------------------------------
# Sidebar tools
# ----------------------------------------------------------------------------------
side_tools:
  enable: false


# ----------------------------------------------------------------------------------
# Back to top
# ----------------------------------------------------------------------------------
back2top:
  enable: false


# ----------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ----------------------------------------------------------------------------------
toc:
  enable: false

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true


# ----------------------------------------------------------------------------------
# Magic
# ----------------------------------------------------------------------------------
magic:
  enable: true
  scale: false    # scale effect when the mouse hover
  shadow: false   # shadow effect when the mouse hover
